title: Tanishka's Blog Page
author: Tanishka Kohli
email: tanishka.kohli0@gmail.com
theme: jekyll-theme-minimal

description: This is my blog website where I share my experience and some notes as well for problems that I solve as Programmer

# social links
twitter_username: kohli00 # DO NOT include the @ character, or else the build will fail!
github_username:  tkohli # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
